# Auto-generated by smoketests/calibrate_tags.py — do not edit by hand.
# Maps destination names to physical AprilTag IDs.
TAG_IDS = {
    'home': 0,
    'table1': 1,
    'table2': 5,
    'table3': 4,
    'table4': 3,
}
