# Auto-generated by smoketests/calibrate_tags.py — do not edit by hand.
# Maps destination names to physical AprilTag IDs.
TAG_IDS = {
    'Home': 0,
    'Table 1': 1,
    'Table 2': 5,
    'Table 3': 4,
    'Table 4': 3,
}
