#!/usr/bin/env python3
"""
AprilTag calibration: assign physical tag IDs to named destinations.

Place each tag in front of the camera when prompted. The script reads the
detected ID and saves the mapping to config.py in the project root.

Usage:
    source venv4sipserve/bin/activate
    python smoketests/calibrate_tags.py
"""

import sys
import os
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, ".."))

from sensors.apriltag import build_pipeline

DESTINATIONS = ["home", "table1", "table2", "table3", "table4"]
CONFIG_PATH = os.path.join(_HERE, "..", "config.py")


def wait_for_stable_tag(q, label: str) -> int:
    """
    Show live detections until the user presses Enter with exactly one tag
    visible and stable for 3 consecutive frames. Returns the confirmed tag ID.
    """
    print(f"\n--- Calibrating: {label!r} ---")
    print("Hold the tag in front of the camera and press Enter when ready.")
    input()

    print("Reading tag... (hold steady)")
    recent = []

    while True:
        tag_msg = q["tags"].get()
        tags = list(tag_msg.aprilTags)
        ids = [t.id for t in tags]

        if len(ids) == 0:
            recent.clear()
            print("  No tag detected — move tag closer.")
            continue

        if len(ids) > 1:
            recent.clear()
            print(f"  Multiple tags visible {ids} — show only one tag at a time.")
            continue

        detected_id = ids[0]
        recent.append(detected_id)

        # Keep only last 3 readings
        if len(recent) > 3:
            recent.pop(0)

        if len(recent) == 3 and len(set(recent)) == 1:
            print(f"  Detected tag ID: {detected_id}")
            confirm = input(f"  Assign tag ID {detected_id} to {label!r}? [Y/n]: ").strip().lower()
            if confirm in ("", "y", "yes"):
                return detected_id
            else:
                recent.clear()
                print("  Retrying — hold the tag in front of the camera and press Enter.")
                input()


def write_config(mapping: dict) -> None:
    lines = [
        "# Auto-generated by smoketests/calibrate_tags.py — do not edit by hand.\n",
        "# Maps destination names to physical AprilTag IDs.\n",
        "TAG_IDS = {\n",
    ]
    for name, tag_id in mapping.items():
        lines.append(f"    {name!r}: {tag_id},\n")
    lines.append("}\n")

    with open(CONFIG_PATH, "w") as f:
        f.writelines(lines)

    print(f"\nSaved to {os.path.abspath(CONFIG_PATH)}")


def main():
    print("SipServe AprilTag calibration")
    print("=" * 40)
    print("You will be asked to present 5 tags in order:")
    for i, name in enumerate(DESTINATIONS, 1):
        print(f"  {i}. {name}")
    print()

    pipeline, q = build_pipeline()
    mapping = {}

    with pipeline:
        pipeline.start()
        try:
            for dest in DESTINATIONS:
                tag_id = wait_for_stable_tag(q, dest)
                mapping[dest] = tag_id
                print(f"  Saved: {dest!r} = tag {tag_id}")
        except KeyboardInterrupt:
            print("\nCalibration aborted.")
            sys.exit(1)
        finally:
            pipeline.stop()

    print("\nCalibration complete:")
    for name, tag_id in mapping.items():
        print(f"  {name}: tag ID {tag_id}")

    write_config(mapping)


if __name__ == "__main__":
    main()
